/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mealmanagementsystem;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leemon
 */
public class DeleteEntry extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public DeleteEntry() {
        initComponents();
        
        
        try { 
            BufferedReader br= new BufferedReader(new FileReader("maindata.txt"));
            int x=0;
            String s;
           while ((s= br.readLine()) !=null)
           {
               String []c= s.split(",");
                 DefaultTableModel model= (DefaultTableModel) showNewTable.getModel();
                 model.addRow( new Object []{++x,c[0],c[1],c[2],c[3],c[4],c[5],c[6]});
               
               
           }
            
            
            
            
            
            
            
        } catch (Exception ex) {
             
        }
        
        
        
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        workPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        showNewTable = new javax.swing.JTable();
        deleteLabel = new javax.swing.JLabel();
        deleteTextField = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        showTabel = new javax.swing.JTable();
        popTextLabel = new javax.swing.JLabel();
        headingPanel = new javax.swing.JPanel();
        headingLabel = new javax.swing.JLabel();
        creatorLabel = new javax.swing.JLabel();
        optionPanel = new javax.swing.JPanel();
        optionLabel = new javax.swing.JLabel();
        entryToggleButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 255));
        setLocation(new java.awt.Point(100, 100));
        setMinimumSize(new java.awt.Dimension(933, 537));

        workPanel.setBackground(new java.awt.Color(102, 255, 102));

        showNewTable.setBackground(new java.awt.Color(102, 255, 255));
        showNewTable.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        showNewTable.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        showNewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sl. No.", "Date", "Leemon", "Siam", "Ridoy", "Sakib", "Rabiul", "Shahriar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(showNewTable);
        if (showNewTable.getColumnModel().getColumnCount() > 0) {
            showNewTable.getColumnModel().getColumn(0).setResizable(false);
            showNewTable.getColumnModel().getColumn(1).setResizable(false);
            showNewTable.getColumnModel().getColumn(2).setResizable(false);
            showNewTable.getColumnModel().getColumn(3).setResizable(false);
            showNewTable.getColumnModel().getColumn(4).setResizable(false);
            showNewTable.getColumnModel().getColumn(5).setResizable(false);
            showNewTable.getColumnModel().getColumn(6).setResizable(false);
            showNewTable.getColumnModel().getColumn(7).setResizable(false);
        }

        deleteLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        deleteLabel.setForeground(new java.awt.Color(0, 0, 0));
        deleteLabel.setText("Enter Serial You Want To Delete!!!!!!!");

        okButton.setBackground(new java.awt.Color(102, 255, 255));
        okButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        okButton.setForeground(new java.awt.Color(0, 0, 0));
        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        showTabel.setBackground(new java.awt.Color(102, 255, 255));
        showTabel.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        showTabel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        showTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sl. No.", "Date", "Leemon", "Siam", "Ridoy", "Sakib", "Rabiul", "Shahriar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(showTabel);

        popTextLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        popTextLabel.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout workPanelLayout = new javax.swing.GroupLayout(workPanel);
        workPanel.setLayout(workPanelLayout);
        workPanelLayout.setHorizontalGroup(
            workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(deleteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(okButton)
                        .addGap(49, 49, 49)
                        .addComponent(popTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addContainerGap())
            .addGroup(workPanelLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(deleteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        workPanelLayout.setVerticalGroup(
            workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(popTextLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(deleteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(okButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addContainerGap())
        );

        headingPanel.setBackground(new java.awt.Color(255, 51, 51));

        headingLabel.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        headingLabel.setText("Meal Management System");

        creatorLabel.setFont(new java.awt.Font("Blackadder ITC", 3, 24)); // NOI18N
        creatorLabel.setForeground(new java.awt.Color(0, 0, 0));
        creatorLabel.setText("By M.Leemon");

        javax.swing.GroupLayout headingPanelLayout = new javax.swing.GroupLayout(headingPanel);
        headingPanel.setLayout(headingPanelLayout);
        headingPanelLayout.setHorizontalGroup(
            headingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(creatorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headingPanelLayout.setVerticalGroup(
            headingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creatorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        optionPanel.setBackground(new java.awt.Color(255, 204, 51));
        optionPanel.setForeground(new java.awt.Color(0, 0, 0));

        optionLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        optionLabel.setForeground(new java.awt.Color(0, 0, 0));
        optionLabel.setText("Options");

        entryToggleButton.setBackground(new java.awt.Color(102, 255, 102));
        entryToggleButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        entryToggleButton.setText("Home Page");
        entryToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryToggleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionPanelLayout = new javax.swing.GroupLayout(optionPanel);
        optionPanel.setLayout(optionPanelLayout);
        optionPanelLayout.setHorizontalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(optionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entryToggleButton))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        optionPanelLayout.setVerticalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(optionLabel)
                .addGap(34, 34, 34)
                .addComponent(entryToggleButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(workPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(workPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(optionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entryToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryToggleButtonActionPerformed
       
              
             Homepage h= new Homepage();
             h.setVisible(true);
             this.setVisible(false);
             
          
         
    }//GEN-LAST:event_entryToggleButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
      try
      {
            String q;
             
             BufferedReader wr= new BufferedReader( new FileReader("maindata.txt"));
                BufferedWriter xr= new BufferedWriter( new FileWriter ("catch.txt"));
               while( (q=wr.readLine()  )!=null)
                       {
                           xr.write(q);
                           
                            
                           xr.newLine();
                           
                       }   
               xr.close();
                 
                BufferedReader sr= new BufferedReader( new FileReader("catch.txt"));
              
               
                            
                
              String z;
                 ArrayList<String > a = new ArrayList();
                  
                 while( (z=sr.readLine()  )!=null)
                       { 
                           
                       
                         a.add(z);
                             
                           
                       }
                 int v= Integer.parseInt(deleteTextField.getText());
                 v--;
              if (   v<a.size()){  
                   BufferedWriter br= new BufferedWriter( new FileWriter ("maindata.txt"));
                 a.remove(v);
               //  String [] xll= new String[a.size()];
               //  xll = (String[]) a.toArray();
                  for( int i=0; i<a.size();i++)
                  {
                      String zz=a.get(i);
                      br.write(zz);
                      br.newLine();
                      
                  }
          br.close();
          
           try { 
            BufferedReader vrr= new BufferedReader(new FileReader("maindata.txt"));
            int x=0;
            String s;
           while ((s= vrr.readLine()) !=null)
           {
               String []c= s.split(",");
                 DefaultTableModel model= (DefaultTableModel) showTabel.getModel();
                 model.addRow( new Object []{++x,c[0],c[1],c[2],c[3],c[4],c[5],c[6]});
               
               
           }
            
            
            
            
            
            
            
        } catch (Exception ex) {
             
        }
           popTextLabel.setText("Successful");
              }
              
              
              else 
              {
                   popTextLabel.setText("Check Serial No. Carefully");
              }
          
      }
      catch(Exception ex)
      {
          
      }
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel creatorLabel;
    private javax.swing.JLabel deleteLabel;
    private javax.swing.JTextField deleteTextField;
    private javax.swing.JToggleButton entryToggleButton;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JPanel headingPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel optionLabel;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JLabel popTextLabel;
    private javax.swing.JTable showNewTable;
    private javax.swing.JTable showTabel;
    private javax.swing.JPanel workPanel;
    // End of variables declaration//GEN-END:variables
}
