/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mealmanagementsystem;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leemon
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
     int leeT=0, siamT=0, ridoyT=0, rabiulT=0, sakibT=0, shahriarT=0;
    public LoginPage() {
        initComponents();
        
         
        try { 
            BufferedReader br= new BufferedReader(new FileReader("maindata.txt"));
            int x=0;
            String s;
           while ((s= br.readLine()) !=null)
           {
               String []c= s.split(",");
               
               leeT= leeT+ Integer.parseInt(c[1]);
               siamT= siamT+ Integer.parseInt(c[2]);
               ridoyT = ridoyT + Integer.parseInt(c[3]);
               sakibT = sakibT + Integer.parseInt(c[4]);
               rabiulT= rabiulT+ Integer.parseInt(c[5]);
               shahriarT= shahriarT + Integer.parseInt(c[6]);
               
                 DefaultTableModel model= (DefaultTableModel) mealTable.getModel();
                 model.addRow( new Object []{++x,c[0],c[1],c[2],c[3],c[4],c[5],c[6]});
               
               leemonTMeal.setText(String.valueOf(leeT));
               siamTMeal.setText(String.valueOf(siamT));
               ridoyTMeal.setText(String.valueOf(ridoyT));
               sakibTMeal.setText(String.valueOf(sakibT));
               rabiulTMeal.setText(String.valueOf(rabiulT));
               shahriarTMeal.setText(String.valueOf(shahriarT));
               
               
           }
            int totalBajar=0;
            BufferedReader wwr= new BufferedReader( new FileReader( "bajar.txt"));
            String sc;
            while( (sc=wwr.readLine())!=null)
            {
                String []cc= sc.split(",");
                totalBajar= totalBajar+ Integer.parseInt(cc[1]);
                
            }
            
            totalBajarLabel.setText(String.valueOf(totalBajar)+"/- Tk.");
            
            double totalMeal= leeT+ siamT+ ridoyT+sakibT+rabiulT+shahriarT;
            double mealRate= totalBajar/totalMeal;
            
            mealRate3.setText(String.valueOf(mealRate));
            mealRate4.setText(String.valueOf(totalMeal));
            
        } catch (Exception ex) {
             
        }
        
        
        
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        workPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mealTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        leemonTMeal = new javax.swing.JLabel();
        siamTMeal = new javax.swing.JLabel();
        ridoyTMeal = new javax.swing.JLabel();
        sakibTMeal = new javax.swing.JLabel();
        rabiulTMeal = new javax.swing.JLabel();
        shahriarTMeal = new javax.swing.JLabel();
        headingPanel = new javax.swing.JPanel();
        headingLabel = new javax.swing.JLabel();
        creatorLabel = new javax.swing.JLabel();
        optionPanel = new javax.swing.JPanel();
        mealRateLabel = new javax.swing.JLabel();
        totalBajarLabel = new javax.swing.JLabel();
        mealRate2 = new javax.swing.JLabel();
        mealRate3 = new javax.swing.JLabel();
        mealRate4 = new javax.swing.JLabel();
        mealRate5 = new javax.swing.JLabel();
        denaPaunaPanel = new javax.swing.JPanel();
        mealRateLabel1 = new javax.swing.JLabel();
        userId = new javax.swing.JTextField();
        okButton2 = new javax.swing.JButton();
        show = new javax.swing.JLabel();
        mealRateLabel3 = new javax.swing.JLabel();
        passWord = new javax.swing.JPasswordField();
        exitButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 255));
        setLocation(new java.awt.Point(100, 100));
        setMinimumSize(new java.awt.Dimension(1103, 613));

        workPanel.setBackground(new java.awt.Color(102, 255, 102));

        mealTable.setBackground(new java.awt.Color(102, 255, 255));
        mealTable.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        mealTable.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        mealTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sl. No.", "Date", "Leemon", "Siam", "Ridoy", "Sakib", "Rabiul", "Shahriar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(mealTable);
        if (mealTable.getColumnModel().getColumnCount() > 0) {
            mealTable.getColumnModel().getColumn(0).setResizable(false);
            mealTable.getColumnModel().getColumn(1).setResizable(false);
            mealTable.getColumnModel().getColumn(2).setResizable(false);
            mealTable.getColumnModel().getColumn(3).setResizable(false);
            mealTable.getColumnModel().getColumn(4).setResizable(false);
            mealTable.getColumnModel().getColumn(5).setResizable(false);
            mealTable.getColumnModel().getColumn(6).setResizable(false);
            mealTable.getColumnModel().getColumn(7).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Total:");

        leemonTMeal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        leemonTMeal.setForeground(new java.awt.Color(0, 0, 0));
        leemonTMeal.setBorder(new javax.swing.border.MatteBorder(null));

        siamTMeal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        siamTMeal.setForeground(new java.awt.Color(0, 0, 0));
        siamTMeal.setBorder(new javax.swing.border.MatteBorder(null));

        ridoyTMeal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ridoyTMeal.setForeground(new java.awt.Color(0, 0, 0));
        ridoyTMeal.setBorder(new javax.swing.border.MatteBorder(null));

        sakibTMeal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        sakibTMeal.setForeground(new java.awt.Color(0, 0, 0));
        sakibTMeal.setBorder(new javax.swing.border.MatteBorder(null));

        rabiulTMeal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rabiulTMeal.setForeground(new java.awt.Color(0, 0, 0));
        rabiulTMeal.setBorder(new javax.swing.border.MatteBorder(null));

        shahriarTMeal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        shahriarTMeal.setForeground(new java.awt.Color(0, 0, 0));
        shahriarTMeal.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout workPanelLayout = new javax.swing.GroupLayout(workPanel);
        workPanel.setLayout(workPanelLayout);
        workPanelLayout.setHorizontalGroup(
            workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(workPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(workPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)
                        .addComponent(leemonTMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(siamTMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ridoyTMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(sakibTMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(rabiulTMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(shahriarTMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))))
        );
        workPanelLayout.setVerticalGroup(
            workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(workPanelLayout.createSequentialGroup()
                        .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(siamTMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ridoyTMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sakibTMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rabiulTMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(leemonTMeal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(shahriarTMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))
                    .addGroup(workPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        headingPanel.setBackground(new java.awt.Color(255, 51, 51));

        headingLabel.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        headingLabel.setText("Meal Management System");

        creatorLabel.setFont(new java.awt.Font("Blackadder ITC", 3, 24)); // NOI18N
        creatorLabel.setForeground(new java.awt.Color(0, 0, 0));
        creatorLabel.setText("By M.Leemon");

        javax.swing.GroupLayout headingPanelLayout = new javax.swing.GroupLayout(headingPanel);
        headingPanel.setLayout(headingPanelLayout);
        headingPanelLayout.setHorizontalGroup(
            headingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(creatorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headingPanelLayout.setVerticalGroup(
            headingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creatorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        optionPanel.setBackground(new java.awt.Color(255, 204, 51));
        optionPanel.setForeground(new java.awt.Color(0, 0, 0));

        mealRateLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mealRateLabel.setForeground(new java.awt.Color(0, 0, 0));
        mealRateLabel.setText("Total Bajar:");

        totalBajarLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        totalBajarLabel.setForeground(new java.awt.Color(0, 0, 0));
        totalBajarLabel.setBorder(new javax.swing.border.MatteBorder(null));

        mealRate2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mealRate2.setForeground(new java.awt.Color(0, 0, 0));
        mealRate2.setText("Meal Rate:");

        mealRate3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mealRate3.setForeground(new java.awt.Color(0, 0, 0));
        mealRate3.setBorder(new javax.swing.border.MatteBorder(null));

        mealRate4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mealRate4.setForeground(new java.awt.Color(0, 0, 0));
        mealRate4.setBorder(new javax.swing.border.MatteBorder(null));

        mealRate5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mealRate5.setForeground(new java.awt.Color(0, 0, 0));
        mealRate5.setText("Total Meal:");

        javax.swing.GroupLayout optionPanelLayout = new javax.swing.GroupLayout(optionPanel);
        optionPanel.setLayout(optionPanelLayout);
        optionPanelLayout.setHorizontalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalBajarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mealRateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mealRate2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mealRate3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mealRate4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mealRate5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        optionPanelLayout.setVerticalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(mealRateLabel)
                .addGap(48, 48, 48)
                .addComponent(totalBajarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(mealRate5)
                .addGap(52, 52, 52)
                .addComponent(mealRate4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(mealRate2)
                .addGap(62, 62, 62)
                .addComponent(mealRate3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        denaPaunaPanel.setBackground(new java.awt.Color(51, 255, 255));

        mealRateLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mealRateLabel1.setForeground(new java.awt.Color(0, 0, 0));
        mealRateLabel1.setText("User ID:");

        okButton2.setBackground(new java.awt.Color(102, 255, 102));
        okButton2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        okButton2.setForeground(new java.awt.Color(0, 0, 0));
        okButton2.setText("ok");
        okButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButton2ActionPerformed(evt);
            }
        });

        show.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        show.setForeground(new java.awt.Color(255, 0, 0));
        show.setBorder(new javax.swing.border.MatteBorder(null));

        mealRateLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mealRateLabel3.setForeground(new java.awt.Color(0, 0, 0));
        mealRateLabel3.setText("Password:");

        exitButton.setBackground(new java.awt.Color(102, 255, 102));
        exitButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout denaPaunaPanelLayout = new javax.swing.GroupLayout(denaPaunaPanel);
        denaPaunaPanel.setLayout(denaPaunaPanelLayout);
        denaPaunaPanelLayout.setHorizontalGroup(
            denaPaunaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(denaPaunaPanelLayout.createSequentialGroup()
                .addGroup(denaPaunaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(denaPaunaPanelLayout.createSequentialGroup()
                        .addGroup(denaPaunaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(denaPaunaPanelLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(okButton2))
                            .addGroup(denaPaunaPanelLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(denaPaunaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mealRateLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userId, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(mealRateLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passWord))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(denaPaunaPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(denaPaunaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(show, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(denaPaunaPanelLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 44, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        denaPaunaPanelLayout.setVerticalGroup(
            denaPaunaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(denaPaunaPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(mealRateLabel1)
                .addGap(18, 18, 18)
                .addComponent(userId, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mealRateLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passWord, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(okButton2)
                .addGap(54, 54, 54)
                .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(exitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(workPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(denaPaunaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(workPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(denaPaunaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(optionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButton2ActionPerformed
         String ss= userId.getText();
         String pass= passWord.getText();
         if ( ss.equals("Admin") && pass.equals("Lee"))
         {
              NewUser h= new NewUser();
             h.setVisible(true);
             this.setVisible(false);
         }
         else 
         {
             show.setText("Invalid Id/password");
         }
    }//GEN-LAST:event_okButton2ActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel creatorLabel;
    private javax.swing.JPanel denaPaunaPanel;
    private javax.swing.JToggleButton exitButton;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JPanel headingPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel leemonTMeal;
    private javax.swing.JLabel mealRate2;
    private javax.swing.JLabel mealRate3;
    private javax.swing.JLabel mealRate4;
    private javax.swing.JLabel mealRate5;
    private javax.swing.JLabel mealRateLabel;
    private javax.swing.JLabel mealRateLabel1;
    private javax.swing.JLabel mealRateLabel3;
    private javax.swing.JTable mealTable;
    private javax.swing.JButton okButton2;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JPasswordField passWord;
    private javax.swing.JLabel rabiulTMeal;
    private javax.swing.JLabel ridoyTMeal;
    private javax.swing.JLabel sakibTMeal;
    private javax.swing.JLabel shahriarTMeal;
    private javax.swing.JLabel show;
    private javax.swing.JLabel siamTMeal;
    private javax.swing.JLabel totalBajarLabel;
    private javax.swing.JTextField userId;
    private javax.swing.JPanel workPanel;
    // End of variables declaration//GEN-END:variables
}
