/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mealmanagementsystem;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Leemon
 */
public class OldEntry extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
   // String c;
    String d;
    public OldEntry() {
        initComponents();
         DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");  
   LocalDateTime now = LocalDateTime.now();  
      d= dtf.format(now);
    dateLabel.setText(d);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        workPanel = new javax.swing.JPanel();
        mealLabel = new javax.swing.JLabel();
        leemonMeal = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        leemonLabel = new javax.swing.JLabel();
        siamLabel = new javax.swing.JLabel();
        ridoyLabel = new javax.swing.JLabel();
        sakibLabel = new javax.swing.JLabel();
        rabiulLabel = new javax.swing.JLabel();
        shahriarLabel = new javax.swing.JLabel();
        siamMeal = new javax.swing.JTextField();
        ridoyMeal = new javax.swing.JTextField();
        sakibMeal = new javax.swing.JTextField();
        rabiulMeal = new javax.swing.JTextField();
        shahriarMeal = new javax.swing.JTextField();
        dateLabel = new javax.swing.JLabel();
        mealLabel1 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        popUpLabel = new javax.swing.JLabel();
        headingPanel = new javax.swing.JPanel();
        headingLabel = new javax.swing.JLabel();
        creatorLabel = new javax.swing.JLabel();
        optionPanel = new javax.swing.JPanel();
        optionLabel = new javax.swing.JLabel();
        entryToggleButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 255));
        setLocation(new java.awt.Point(100, 100));
        setMinimumSize(new java.awt.Dimension(1103, 613));

        workPanel.setBackground(new java.awt.Color(102, 255, 102));

        mealLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        mealLabel.setForeground(new java.awt.Color(0, 0, 0));
        mealLabel.setText("No. of Meal:");

        leemonMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leemonMealActionPerformed(evt);
            }
        });

        okButton.setBackground(new java.awt.Color(0, 204, 153));
        okButton.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        okButton.setText("Add Entry");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        leemonLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        leemonLabel.setForeground(new java.awt.Color(0, 0, 0));
        leemonLabel.setText("Leemon");

        siamLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        siamLabel.setForeground(new java.awt.Color(0, 0, 0));
        siamLabel.setText("Siam");

        ridoyLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ridoyLabel.setForeground(new java.awt.Color(0, 0, 0));
        ridoyLabel.setText("Ridoy");

        sakibLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        sakibLabel.setForeground(new java.awt.Color(0, 0, 0));
        sakibLabel.setText("Sakib");

        rabiulLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rabiulLabel.setForeground(new java.awt.Color(0, 0, 0));
        rabiulLabel.setText("Rabiul");

        shahriarLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        shahriarLabel.setForeground(new java.awt.Color(0, 0, 0));
        shahriarLabel.setText("Shahriar");

        siamMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siamMealActionPerformed(evt);
            }
        });

        ridoyMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ridoyMealActionPerformed(evt);
            }
        });

        sakibMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sakibMealActionPerformed(evt);
            }
        });

        rabiulMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rabiulMealActionPerformed(evt);
            }
        });

        shahriarMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shahriarMealActionPerformed(evt);
            }
        });

        dateLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(0, 0, 0));

        mealLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        mealLabel1.setForeground(new java.awt.Color(0, 0, 0));
        mealLabel1.setText("Date(yy/mm/dd):");

        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });

        popUpLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        popUpLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout workPanelLayout = new javax.swing.GroupLayout(workPanel);
        workPanel.setLayout(workPanelLayout);
        workPanelLayout.setHorizontalGroup(
            workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okButton)
                .addGap(293, 293, 293))
            .addGroup(workPanelLayout.createSequentialGroup()
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(workPanelLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(shahriarMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(workPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(mealLabel1)
                        .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(workPanelLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mealLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(workPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(workPanelLayout.createSequentialGroup()
                                                .addComponent(rabiulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(rabiulMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(workPanelLayout.createSequentialGroup()
                                                .addComponent(ridoyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(ridoyMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(workPanelLayout.createSequentialGroup()
                                                .addComponent(siamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(siamMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(workPanelLayout.createSequentialGroup()
                                                .addComponent(sakibLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(sakibMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(shahriarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workPanelLayout.createSequentialGroup()
                                        .addComponent(leemonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(leemonMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(workPanelLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(popUpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        workPanelLayout.setVerticalGroup(
            workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mealLabel)
                        .addComponent(mealLabel1)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leemonMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leemonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(siamMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ridoyMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ridoyLabel))
                .addGap(28, 28, 28)
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sakibMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sakibLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rabiulMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rabiulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shahriarMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shahriarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(okButton)
                .addGap(18, 18, 18)
                .addComponent(popUpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        headingPanel.setBackground(new java.awt.Color(255, 51, 51));

        headingLabel.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        headingLabel.setText("Meal Management System");

        creatorLabel.setFont(new java.awt.Font("Blackadder ITC", 3, 24)); // NOI18N
        creatorLabel.setForeground(new java.awt.Color(0, 0, 0));
        creatorLabel.setText("By M.Leemon");

        javax.swing.GroupLayout headingPanelLayout = new javax.swing.GroupLayout(headingPanel);
        headingPanel.setLayout(headingPanelLayout);
        headingPanelLayout.setHorizontalGroup(
            headingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(creatorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headingPanelLayout.setVerticalGroup(
            headingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creatorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        optionPanel.setBackground(new java.awt.Color(255, 204, 51));
        optionPanel.setForeground(new java.awt.Color(0, 0, 0));

        optionLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        optionLabel.setForeground(new java.awt.Color(0, 0, 0));
        optionLabel.setText("Options");

        entryToggleButton.setBackground(new java.awt.Color(102, 255, 102));
        entryToggleButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        entryToggleButton.setText("Home Page");
        entryToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryToggleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionPanelLayout = new javax.swing.GroupLayout(optionPanel);
        optionPanel.setLayout(optionPanelLayout);
        optionPanelLayout.setHorizontalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entryToggleButton))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        optionPanelLayout.setVerticalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(optionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entryToggleButton)
                .addContainerGap(537, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(workPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(workPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(optionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entryToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryToggleButtonActionPerformed
       
              
            Homepage h= new Homepage();
            h.setVisible(true);
            this.setVisible(false);
          
         
    }//GEN-LAST:event_entryToggleButtonActionPerformed

    private void leemonMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leemonMealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leemonMealActionPerformed
     
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        String s= leemonMeal.getText(), s1= siamMeal.getText(), s2= ridoyMeal.getText(), s3= sakibMeal.getText(), s4 = rabiulMeal.getText(), s5= shahriarMeal.getText();
       String s6=date.getText();
       
       
           
       if ( s.isEmpty() || s1.isEmpty() || s2.isEmpty() || s3.isEmpty() || s4.isEmpty() || s5.isEmpty() || s6.isEmpty())
       {
             popUpLabel.setText("NOT SUCCESSFUL ! Please Enter All The Data!!");
       }
        
       
     if (s.isEmpty()==false && s1.isEmpty()==false && s2.isEmpty()==false && s3.isEmpty()==false && s4.isEmpty()==false && s5.isEmpty()==false && s6.isEmpty()==false) { 
       try {   String q;
                            
               BufferedReader wr= new BufferedReader( new FileReader("maindata.txt"));
                BufferedWriter xr= new BufferedWriter( new FileWriter ("catch.txt"));
               while( (q=wr.readLine()  )!=null)
                       {
                           xr.write(q);
                           
                            
                           xr.newLine();
                           
                       }   
               xr.close();
                 
                BufferedReader sr= new BufferedReader( new FileReader("catch.txt"));
               BufferedWriter br= new BufferedWriter( new FileWriter ("maindata.txt"));
               
                            
                
              
                 br.write(s6+","+s+","+s1+","+s2+","+s3+","+s4+","+s5);
                 br.newLine();
                 while( (q=sr.readLine()  )!=null)
                       {
                           br.write(q);
                           br.newLine();
                           
                       }    
                // br.newLine();
                 br.close();

                 
               popUpLabel.setText("Successful!!");
               
               
               
           } catch (Exception ex) {
                
           }
     } 
       
    }//GEN-LAST:event_okButtonActionPerformed

    private void siamMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siamMealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_siamMealActionPerformed

    private void ridoyMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ridoyMealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ridoyMealActionPerformed

    private void sakibMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sakibMealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sakibMealActionPerformed

    private void rabiulMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rabiulMealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rabiulMealActionPerformed

    private void shahriarMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shahriarMealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shahriarMealActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel creatorLabel;
    private javax.swing.JTextField date;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JToggleButton entryToggleButton;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JPanel headingPanel;
    private javax.swing.JLabel leemonLabel;
    private javax.swing.JTextField leemonMeal;
    private javax.swing.JLabel mealLabel;
    private javax.swing.JLabel mealLabel1;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel optionLabel;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JLabel popUpLabel;
    private javax.swing.JLabel rabiulLabel;
    private javax.swing.JTextField rabiulMeal;
    private javax.swing.JLabel ridoyLabel;
    private javax.swing.JTextField ridoyMeal;
    private javax.swing.JLabel sakibLabel;
    private javax.swing.JTextField sakibMeal;
    private javax.swing.JLabel shahriarLabel;
    private javax.swing.JTextField shahriarMeal;
    private javax.swing.JLabel siamLabel;
    private javax.swing.JTextField siamMeal;
    private javax.swing.JPanel workPanel;
    // End of variables declaration//GEN-END:variables
}
